
default_platform(:android)

platform :android do
  desc "Distribute production build to Firebase"
  lane :release_app do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"

    firebase_app_distribution(
      app: "1:754897613485:android:8cea1548a7dd94d6874c24",
      firebase_cli_token: ENV["firebase_cli_token"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "aelbaz0189@gmail.com",
      release_notes: "test this version of the app"
    )
  end
end
