name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main # غيّرها لـ master لو هو الفرع الأساسي عندك

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Setup Ruby & Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
          bundler-cache: false   # نخلي الكاش false علشان نتحكم في bundler
          working-directory: android

      - name: Add Linux platform to Gemfile.lock
        working-directory: android
        run: |
          bundle lock --add-platform x86_64-linux || true
          bundle lock --add-platform x64-mingw-ucrt || true
          bundle lock --add-platform x86_64-darwin-21 || true

      - name: Install dependencies (bundle install)
        working-directory: android
        run: bundle install --jobs 4

      - name: Build and Distribute App to Firebase
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane android release_to_firebase
        working-directory: android

      # Upload APK as Artifact (optional but useful)
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/*.apk
